# version: '3.8'

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    # depends_on:
    #   - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    networks:
      - app-network
    
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    # healthcheck:
    #   test: ["CMD", "mysqladmin", "ping", "--socket=/run/mysqld/mysqld.sock", "--silent"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 30s

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASS}
      DOMAIN_NAME: ${DOMAIN_NAME}
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN_N: ${WP_ADMIN_N}
      WP_ADMIN_P: ${WP_ADMIN_P}
      WP_ADMIN_E: ${WP_ADMIN_E}
      WP_U_NAME: ${WP_U_NAME}
      WP_U_PASS: ${WP_U_PASS}
      WP_U_EMAIL: ${WP_U_EMAIL}
      WP_U_ROLE: ${WP_U_ROLE}
    ports:
      - "9000:9000"
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    networks:
      - app-network

networks:
  app-network:
    name: app-network

volumes:
  db_data:
  wordpress_data: